project:
  type: manuscript
  render:
    - "paper.md"

manuscript:
  article: paper.md
  meca-bundle: true
  code-links:
    - text: Code Repository
      icon: file-code
      href: https://github.com/haiiliin/quarto-template/

format:
  jats: default
  html:
    toc: true
    code-fold: true
  preprint-docx: default

  # https://github.com/quarto-journals/elsevier
  elsevier-pdf:
    keep-tex: true
    fig-pos: "!htb"
    journal:
      name: Computers and Geotechnics
      formatting: review
      model: 3p
      layout: onecolumn
      cite-style: authoryear
      # graphical-abstract: |
      #   Graphical abstract
      # highlights:
      #   - Highlight 1
      #   - Highlight 2
      #   - Highlight 3

  # # https://github.com/juliantao/quarto-asce
  # asce-pdf:
  #   keep-tex: true
  #   fig-pos: "!htb"
  #   classoption:
  #   - InsideFigs
  #   - DoubleSpace
  #   publication-type: Journal
  #   footer-lastname: Wang

  # # https://github.com/ramiromagno/wiley-njd
  # wiley-njd-pdf:
  #   keep-tex: true
  #   fig-pos: "!htb"
  #   classoption:
  #     - AMA
  #     - Times1COL
  #   article-type: "Research Article"
  #   author-mark: "WANG \\textsc{et al.}"
  #   title-mark: "PLEASE INSERT YOUR ARTICLE TITLE HERE"
  #   received: "Date Month Year"
  #   revised: "Date Month Year"
  #   accepted: "Date Month Year"
  #   journal: "Int J Numer Anal Methods Geomech"
  #   volume: "00"
  #   issue: "00"
  #   pages: "1--18"
  #   year: 2024
  #   copy-year: 2024
  #   present-address: "This is sample for present address text this is sample for present address text."
  #   funding-info: ""
  #   abbreviations-note: ""
