project:
  type: website

comments:
  hypothesis: true

manuscript:
  article: paper.md
  meca-bundle: true
  code-links:
    - text: Code Repository
      icon: file-code
      href: https://github.com/haiiliin/quarto-template/

website:
  title: Hailin Wang
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/haiiliin/quarto-template
  repo-actions: [edit, issue]
  search: true
  navbar:
    background: primary
    search: true
    tools:
      - icon: house
        href: https://hailin.wang/
      - icon: github
        menu:
          - text: Home Page
            href: https://github.com/haiiliin/
          - text: Source Code
            href: https://github.com/haiiliin/quarto-template/
  sidebar:
    style: docked
    collapse-level: 1
    contents: auto

format:
  jats: default
  html:
    toc: true
    code-fold: true
    appendix-cite-as: display
    link-external-newwindow: true
    format-links:
      - preprint-docx
      - elsevier-pdf
      - text: PDF (latexdiff)
        icon: file-pdf
        href: paper-diff.pdf
    filters:
      - critic-markup
  preprint-docx:
    filters:
      - abstract.lua
      - authors-block

  # https://github.com/quarto-journals/elsevier
  elsevier-pdf:
    keep-tex: true
    fig-pos: "!htb"
    include-in-header:
      - text: |
          \usepackage{ctex}
    journal:
      name: Computers and Geotechnics
      formatting: review
      model: 3p
      layout: onecolumn
      cite-style: authoryear
      # graphical-abstract: |
      #   Graphical abstract
      # highlights:
      #   - Highlight 1
      #   - Highlight 2
      #   - Highlight 3

  # # https://github.com/juliantao/quarto-asce
  # asce-pdf:
  #   keep-tex: true
  #   fig-pos: "!htb"
  #   include-in-header:
  #     - text: |
  #         \usepackage{ctex}
  #   classoption:
  #   - InsideFigs
  #   - DoubleSpace
  #   publication-type: Journal
  #   footer-lastname: Wang

  # # https://github.com/ramiromagno/wiley-njd
  # wiley-njd-pdf:
  #   keep-tex: true
  #   fig-pos: "!htb"
  #   include-in-header:
  #     - text: |
  #         \usepackage{ctex}
  #   classoption:
  #     - AMA
  #     - Times1COL
  #   article-type: "Research Article"
  #   author-mark: "WANG \\textsc{et al.}"
  #   title-mark: "PLEASE INSERT YOUR ARTICLE TITLE HERE"
  #   received: "Date Month Year"
  #   revised: "Date Month Year"
  #   accepted: "Date Month Year"
  #   journal: "Int J Numer Anal Methods Geomech"
  #   volume: "00"
  #   issue: "00"
  #   pages: "1--18"
  #   year: 2024
  #   copy-year: 2024
  #   present-address: "This is sample for present address text this is sample for present address text."
  #   funding-info: ""
  #   abbreviations-note: ""
