name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
  release:
    types: [published]

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.33
          tinytex: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup pandoc
        uses: pandoc/actions/setup@v1

      - name: Get the latest version
        run: |
          echo "version=$(cat releases/VERSION || echo '')" >> $GITHUB_ENV

      - name: Generate changes
        if: env.version != '' && 0 == 1
        run: |
          if [ -d "releases/$version" ]; then
            npm install -g pandiff
            make change-$version
          fi

      - name: Render Quarto Project
        run: |
          make deps paper

      - name: Upload release assets
        if: github.event_name == 'release'
        run: |
          zip -r paper-${{ github.ref_name }}.zip outputs
          gh release upload ${{ github.ref_name }} paper-${{ github.ref_name }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build diff for the latest changes
        if: env.version != ''
        run: |
          if [ -d "releases/$version" ]; then
            echo "latexdiff=true" >> $GITHUB_ENV
            sudo apt update
            sudo apt install -y latexdiff texlive-latex-extra texlive-xetex texlive-publishers texlive-lang-chinese

            make release-$sha
            make diff previous=$version current=$sha
            cp releases/$sha/paper-diff-$version-$sha.pdf outputs/paper-diff.pdf
          fi

      - name: Upload latexdiff assets
        if: env.latexdiff == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          path: releases/${{ env.sha }}

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: outputs
          force_orphan: true
