name: Quarto Publish

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [published]

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render Quarto Project
        run: |
          quarto install tinytex
          make fetch paper clean
      - name: Upload release assets
        if: github.event_name == 'release'
        run: |
          zip -r outputs.zip outputs
          gh release upload ${{ github.ref_name }} outputs.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        if: github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: outputs
          force_orphan: true
