name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yml"
      - "paper.md"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yml"
      - "paper.md"
  release:
    types: [published]

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render Quarto Project
        run: |
          quarto install tinytex
          make fetch paper clean
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "outputs"
      - name: Upload release assets
        if: github.event_name == 'release'
        run: |
          gh release upload ${{ github.ref_name }} outputs/*.docx --clobber
          gh release upload ${{ github.ref_name }} outputs/*.md   --clobber
          gh release upload ${{ github.ref_name }} outputs/*.pdf  --clobber
          gh release upload ${{ github.ref_name }}         *.bst  --clobber || true
          gh release upload ${{ github.ref_name }}         *.cls  --clobber || true
          gh release upload ${{ github.ref_name }}         *.sty  --clobber || true
          gh release upload ${{ github.ref_name }}         *.tex  --clobber || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
